comments = ['Amazing work!',
        'Looks awesome!!',
        'Omg this is amazing!',
        'I love it !!!!',
        'Amazing work!',
        'Your drawings are amazing !!!',
        'Love the colour :))',
        'Niiiiccce',
        'Wow!',
        'This is so amazing LOL! Keep it up!',
        'Beautiful',
        'I love your art',
        'I love your beautiful art !',
        'Nice coloring :)!',
        'This is so beautiful!!',
        'I love your art! Keep it coming!',
        'Wow...',
        'Beautiful piece of work',
        'Cute',
        'Your art is like so cool',
        'Amazing work',
        'So pretty',
        'This is really pretty',
        'Love it!!',
        'So cool',
        'Beautiful',
        'I love it!',
        'Love this!!!',
        'Beautiful work!',
        '100/100 love this!',
        'So cool!! :)',
        'Love it',
        'Good job!',
        'I love your artworks!',
        'Inspiring work!',
        'Awesome. Just beautiful!',
        'I love your art!!!',
        'Love it!',
        'You\'re amazing at this!',
        'Incredible artwork!',
        'Amazing work!',
        'This is so good!',
        'Love your art!!',
        'Wow, amazing work!',
        'I love it!!! Beautiful artwork',
        'Your are an incredible artist!',
        'So good',
        'Absolutely amazing!!',
        'Just a brilliant piece of work!',
        'Beautifully done',
        'This is marvelous!',
        'Beautiful!',
        'This is awesomely beautiful...',
        'Just made my day',
        'Wow love this!',
        'Stunning',
        'Love all your work, keep it up!',
        'That was beautiful',
        'So incredibly beautiful ☺',
        'Just breathtaking',
        'Fabulous job!!!',
        'This is so beautiful',
        'Keep up the amazing work!',
        'I love it thank you very much',
        'Wow!',
        'Brilliant',
        'Wow cool piece of work! Awesome.',
        'Just simply amazing',
        'Gorgeous work!',
        'I love it!!!',
        'Awesome. Just awesome.',
        'Absolutely stunning',
        'Wow, amazing piece of art :))',
        'So talented!',
        'Beautiful love it',
        'I really fancy this one',
        'Love it!!!!',
        'wow so nice!!',
        'This is beautiful OMG LOVE IT',
        'WOW',
        'love your work!',
        'Amazing image!',
        'Excellent work capturing this rare type',
        'Beautiful <3',
        'Amazing! Love it !',
        'Gorgeous',
        'Stunning work',
        'Amazing piece of artwork',
        'That\'s awesome, nice work!',
        'Absolutely beautiful!',
        'This is gorgeous',
        'Love it 100%',
        'Spectacular',
        'That is gorgeous',
        'Wow! This is beautiful',
        'I love this so much. It really made my today!',
        'Wow! Thank you so much. You do an excellent job, love your work! Keep up the great work',
        'i absolutely LOVE your work!!',
        'Wow! Absolutely stunning',
        'That\'s gorgeous!! Great job :D',
        'I can see the effort and passion that you put into your art. Awesome stuff ! Like it a lot !!!',
        'Beautiful <3 Thank you so much for sharing!',
        'So beautiful!! Thank you very much!',
        'Amazing! I love it',
        'OMG they look amazing. Thank you for sharing!',
        'So lovely, such talent my friend! <',
        'Great art! Have a nice day. <3',
        'Wow I like it',
        'Your work is really beautiful',
        'Awesome art and thanks for sharing with us',
        'I love it so much <3',
        'Amazing art <3',
        'Wow! I like your work! It\'s very lovely',
        'I love how real this looks...it\'s amazing',
        'Wow!!! This is truly art!',
        'Awesome art <3 Thank u',
        'What a beautiful work. very Inspiring!!!',
        'Amazing work! Absolutely gorgeous pieces',
        'Awesome art and thanks for sharing with us',
        'I love it so much <3',
        'Amazing art <3',
        'This is really cool!',
        'Amazing!!! Loving it!!',
        'Wow! I like your work! It\'s very lovely',
        'I love how real this looks...it\'s amazing',
        'Wow!!! This is truly artistic!',
        'Awesome art <3 Thank you',
        'Wow I love it',
        'This is awesome',
        'What a beautiful work Inspiration!!!',
        'Lovely work!',
        'Stunning, I\'ll be watching for your next masterpiece. ;-)',
        'So beautiful <3 Thank you for sharing',
        'Amazing !!!! I love the textures and colours',
        'Great work !!!',
        'Thanks so much for sharing this.. Amazing work...love it!! <3',
        'I love what you\'ve done here. Please keep it up : )',
        'Really cool! Nicely done.',
        'Its awesome thank you for sharing',
        'Absolutely breathtaking.',
        'This is incredible work! I love it !!! Awesome!!',
        'Truly beautiful <3 these paintings. Wow & wow!!!',
        'amazing art!',
        'Wow! So cool and I love it !!! <3',
        'WOW! Thanks for sharing :)',
        'OMG !! Love it !!! Thank you so much : )',
        'Really amazing. A pleasure to look at. The composition is great here too. Beautiful',
        'Cool stuff !!!! I love the details in your paintings!']

import numpy as np
comments.sort()
for x in comments:
    print(x)

# for x in range(len(comments) '1):
#     print(np.random.choice(comments, replace=False))