comments = [u'Amazing work! ❤️',
        u'Looks awesome!! 😍',
        u'Omg this is amazing! 🔥',
        u'I love it !!!! 🤗',
        u'Amazing work! 🤩',
        u'Your drawings are amazing !!! 💯',
        u'Love the colour :)) 💯',
        u'Niiiiccce 🔥',
        u'Wow! 👏',
        u'This is so amazing LOL! Keep it up! ❤️',
        u'Beautiful 🔥',
        u'I love your art 👍',
        u'I love your beautiful art ! 😍❤️⭐️',
        u'Nice coloring :)!',
        u'This is so beautiful!! 😍❤️',
        u'I love your art! Keep it coming! 😁',
        u'Wow... 👏👏',
        u'Beautiful piece of work 👏',
        u'Cute 😍',
        u'Your art is like so cool 😝💯',
        u'Amazing work 👏',
        u'So pretty 💕',
        u'This is really pretty ❤️',
        u'Love it!',
        u'So cool 😎',
        u'Beautiful 💕',
        u'I love it 😍',
        u'So beautiful 💕',
        u'Love this ⭐️',
        u'Beautiful work! 😊',
        u'100/100 love this!',
        u'So cool 😎🙆👌',
        u'Love it ❤️❤️',
        u'Good job! 👍❤️',
        u'I love your artworks!',
        u'Inspiring work! 😊',
        u'Awesome. Just beautiful! 🙌👌',
        u'I love your art!!! ❤️😍',
        u'Love it! 👍',
        u'You\'re amazing haha 😁',
        u'Incredible artwork! ❤️',
        u'Amazing work 😍❤️',
        u'This is so good!',
        u'Love your art!! ❤️',
        u'Wow, amazing work! 😃',
        u'I love it!!! Beautiful artwork 😊',
        u'Your are an incredible artist ⭐️',
        u'So good',
        u'Absolutely amazing!!',
        u'Just a brilliant piece of work!',
        u'Beautifully done',
        u'This is marvelous! 😍😍👏',
        u'Beautiful! 😃',
        u'This is awesomely beautiful... ❤️',
        u'Just made my day 😄',
        u'Wow love this! 😇👌',
        u'Stunning 💯👍❤️',
        u'Love all your work, keep it up! ⭐️️⭐️',
        u'That was beautiful 😀✨',
        u'So incredibly beautiful ☺',
        u'Just breathtaking',
        u'👏👏👏 Fabulous job!!!',
        u'This is so beautiful 😍❤️',
        u'Keep up the amazing work! 🙂 ❤️',
        u'I love it thank you very much 😍',
        u'Wow! 🙌',
        u'Brilliant 👍👍',
        u'Wow cool piece of work! Awesome. 👏👏',
        u'Just simply amazing 😘',
        u'Gorgeous work!',
        u'I love it!!! 😍✨✨',
        u'Awesome. Just awesome.',
        u'Absolutely stunning 👍',
        u'Wow, amazing piece of art :))',
        u'So talented! 👏💕👌',
        u'Beautiful 🙂 love it 😍😘',
        u'I really fancy this one 😻',
        u'Love it!!!!❤️❤️',
        u'wow so nice!!',
        u'This is beautiful OMG LOVE IT',
        u'WOW',
        u'love your work!🙌',
        u'Amazing image!',
        u'💚 Excellent work capturing this rare type',
        u'Beautiful <3',
        u'Amazing! Love it !',
        u'Gorgeous 😍',
        u'Stunning work 👌',
        u'Amazing piece of artwork',
        u'That\'s awesome, nice work! 🙂',
        u'Absolutely beautiful!! ❤️❤️',
        u'This is gorgeous',
        u'Love it 100%',
        u'Spectacular 😍😍',
        u'Love this! ❤️❤️',
        u'That is gorgeous',
        u'Wow! This is beautiful',
        u'I love this so much. It really made my today!',
        u'Looks lovely 🍁',
        u'This is gorgeous! 👏👏👏',
        u'Love it 😘',
        u'Amazing, cool and beautiful 👏👏👏',
        u'Wow! Thank you so much. You do an excellent job, love your work! Keep up the great work',
        u'i absolutely LOVE your work!!',
        u'Great!! 👏',
        u'So beautiful 💓💓',
        u'Wow! Absolutely stunning',
        u'That\'s gorgeous!! Great job :D',
        u'I can see the effort and passion that you put into your art. Awesome stuff ! Like it a lot !!!',
        u'Beautiful <3 Thank you so much for sharing!',
        u'So beautiful!! Thank you very much!👏',
        u'Amazing! I love it',
        u'Cool stuff 😎👍',
        u'OMG they look amazing. Thank you for sharing!',
        u'So lovely, such talent my friend! <',
        u'Great art! Have a nice day. <3',
        u'Wow I like it',
        u'Terrific work on this! Love it so much! 👌😍💖Thanks for sharing this with us...👏 ',
        u'Your work is really beautiful',
        u'Amazing work! 😍 Absolutely gorgeous pieces',
        u'Awesome art and thanks for sharing with us',
        u'I love it so much <3',
        u'Amazing art <3',
        u'This is really cool!😍',
        u'Amazing!!! Loving it!!😍❤️',
        u'Wow! I like your work! It\'s very lovely',
        u'I love how real this looks...it\'s amazing',
        u'Wow!!! This is truly art!',
        u'Awesome art <3 Thank you',
        u'Wow I love it 😍❤️',
        u'This is awesome 👌',
        u'What a beautiful work Inspiration!!!']

# import numpy as np
# comments.sort()
# for x in comments:
#     print(x)

# for x in range(len(comments) - 1):
#     print(np.random.choice(comments, replace=False))